### ISSUE TITLE
Join Mattermost integrations community channel?

### ISSUE THREAD

**Issue by jasonblais** [CGenie/mattermost-openresty#1]
Hi @CGenie,

Thank you for sharing your project with us, great work with the BitBucket and Sentry integrations! 

We'd also like to welcome you to join the [integrations community channel on our nightly builds server](https://pre-release.mattermost.com/core/channels/integrations), if you'd like and haven't yet.

Wonderful work! Can't wait to share it with the rest of the Mattermost community!

**Comment by CGenie** [comment]
Done!
